name: monarch_easy_localization_sample
description: Monarch sample code and stories using easy_localization package

publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  monarch_annotations: ^1.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  monarch: ^3.0.0
  build_runner: ^2.1.11

flutter:
  assets:
    - assets/translations/

  uses-material-design: true

