name: monarch_samples_patterns
description: Monarch sample code and stories using several patterns

publish_to: 'none' 
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.1
  flutter_bloc: ^7.0.0
  bloc: ^7.0.0
  equatable: ^2.0.0

  cupertino_icons: ^1.0.2

  #animations
  lottie: ^1.0.1

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  monarch: ^2.1.0-pre.2

flutter:
  assets:
    - locale/i18n_en.json
    - locale/i18n_es.json
    - assets/

  uses-material-design: true

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/google_fonts/OpenSans-Light.ttf
          weight: 300
          style: normal
        - asset: assets/google_fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/google_fonts/OpenSans-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/google_fonts/OpenSans-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/google_fonts/OpenSans-SemiBold.ttf
          weight: 500
          style: normal
        - asset: assets/google_fonts/OpenSans-SemiBoldItalic.ttf
          weight: 500
          style: italic
        - asset: assets/google_fonts/OpenSans-Bold.ttf
          weight: 600
        - asset: assets/google_fonts/OpenSans-BoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/google_fonts/OpenSans-ExtraBold.ttf
          weight: 700
        - asset: assets/google_fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 700
          style: italic
