name: monarch_samples_intl_tools
description: Monarch sample code and stories using intl package and tools

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  monarch: ^2.1.0
  build_runner: ^2.1.0

flutter:
  generate: true
  uses-material-design: true
