name: samples_riverpod
description: Monarch sample code and stories using Riverpod.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  monarch: ^3.0.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true